### ISSUE TITLE
HTTP endpoint with metrics for Tarantool 3

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/metrics-export-role#2]
Cartridge allows to export metrics into Prometheus/JSON via HTTP. We need the same ability to export metrics from Tarantool instances into the grafana-dashboard (Tarantool <-> Prometheus <-> grafana-dashboard).
 
 It could be implemented with a Tarantool 3 role as it is already done for the [Cartridge](https://github.com/tarantool/cartridge-metrics-role). The implementation is expected to be a copy-paste of the `cartridge-metrics-role`. The key difference - we will not need to export `/health`.

## List of tasks implementing
- [x] https://github.com/tarantool/metrics-export-role/issues/4
- [x] https://github.com/tarantool/metrics-export-role/issues/6
- [x] https://github.com/tarantool/metrics-export-role/issues/5
